


export const CONFIG = {
  CACHE_TTL: 30 * 60 * 1000, // 30 minutes for recipes
  REQUEST_TIMEOUT: 15000,
  SERVER_REQUEST_TIMEOUT: 20000,
  RETRY_ATTEMPTS: 3,
  RETRY_DELAY: 1000,
  MAX_CACHE_SIZE: 100,
} as const;

export const ERROR_CODES = {
  NOT_FOUND: 'NOT_FOUND',
  NETWORK_ERROR: 'NETWORK_ERROR',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  TIMEOUT_ERROR: 'TIMEOUT_ERROR',
  UNKNOWN_ERROR: 'UNKNOWN_ERROR',
} as const;